config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :item
root 'item#index' 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
    
    def index
        @item = Item.all
    end

    def show
        @item = Item.find(params[:id])
    end

    def new
        @item = Item.new
    end

    def create  
        @item = Item.new(item_params)   
        if @item.save   
          flash[:notice] = 'Item added!'   
          redirect_to root_path   
        else   
          flash[:error] = 'Failed to edit item!'   
          render :new   
        end   
    end 

    def destroy 
      @item = Item.find(params[:id])
      @item.destroy
      flash[:success] = "The item was successfully destroyed."
      redirect_to root_path
        # @item = Item.find(params[:id])   
        # if @item.update_attributes(item_params)   
        #   flash[:notice] = 'Item deleted!'   
        #   redirect_to root_path   
        # else   
        #   flash[:error] = 'Failed to edit item!'   
        #   render :edit   
        # end   
    end

    def item_params   
        params.require(:item).permit(:name, :price, :description)   
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/item/_header.html.erb
<nav class="navbar navbar-expand-lg  bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">eCommerce</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item active">
        <% if admin_user_signed_in? %>
          <%= link_to "Sign Out", destroy_admin_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to "Sign In", new_admin_user_session_path, class: "nav-link" %>
        <% end %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Mobile</a></li>
            <li><a class="dropdown-item" href="#">Cloths</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Watches</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/item/index.html.erb
<%= render 'header' %>
<div class="container card bg-light">
  <h3>Item LIST</h3>   
    <div>   
       <%= link_to 'Add item', new_item_path %>  
    </div>   
      <br> 

    <div class="row">
          <% @item.each do |item| %> 
            <div class="col-md-3">
              <div class="card" style="width: 16rem; margin:10px">
               <img src="assets/ecom.jpg" alt="this is my image" />
                <div class="card-body bg-light  ">
                  <h5 class="card-title"><%= item.name %></h5>
                  <h6 class="card-title">Price <%= item.price %></h6>
                  <p class="card-text"><%= item.description %></p>
                  <%= link_to 'Delete', item_path(item), method: :delete %>   
                  <a href="#" class="btn btn-primary">Add to card</a>
                </div>
              </div>
            </div>
            <br>
          <% end %>
        
    </div>
</div>

app/views/item/new.html.erb
<div class="container card bg-light">   
  <%= form_for @item, url: {action: :create} do |f| %>   
    <div>   
      <h3>Add a item</h3>   
    </div>   
      <div>   
        <p>   
          <div>   
            <label>Item Name  :</label>   
            <%= f.text_field :name %>   
          </div>   
  
          <div>   
            <label>Price      :</label>   
            <%= f.text_field :price %>   
          </div>   
  
          <div>   
            <label>Description:</label>   
            <%= f.text_field :description %>   
          </div>   
        </p>   
      </div>   
    <div>   
      <%= link_to 'Back', { controller: 'item', action: 'index'} %>   
      <%= f.submit 'Create item' %>   
    </div>   
  <% end %>   
</div>  

app/views/item/show.html.erb
<%= render 'header' %>
<div class="container card" >               
  <div>   
    <label>item Name</label>   
    <%= @item.name %>   
  </div>   
  
  <div>   
    <label>Price</label>   
    <%= @item.price %>   
  </div>   
            
  <div>   
    <label>Description</label>   
    <%= @item.description %>   
  </div>   
         
    <div>   
      <%= link_to 'Back', { controller: 'item', action: 'index'} %>   
    </div>   
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">  
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>  
          
    </div>  
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>  
    <%= javascript_include_tag 'https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.js' %> 
  </body>
</html>